repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
        require_serial: true
        stages: [commit, push, manual]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
        require_serial: true
      - id: reorder-python-imports
        name: Reorder python imports
        entry: poetry run reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=src]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.2
    hooks:
      - id: prettier
